### ISSUE TITLE
TypeError: 'GenericMeta' object does not support item assignment

### ISSUE THREAD

**Issue by orenliber** [orisano/olll#1]
Hi,

I'm trying to run the example you have provided and i'm getting the following error:
TypeError: 'GenericMeta' object does not support item assignment
with reference to: 
u:  List[Vector] = []

can you please advise?
Thanks!

**Comment by orisano** [comment]
please give me your environment information and full stack trace

**Comment by orenliber** [comment]
Hi,

Thanks for the feedback.

I'm using:
* Python 3.4.3 :: Anaconda custom (32-bit)
* Windows 10, Version 1803 (OS Build 17134.472)
* Spyder 2.3.5.2

The code I tried to run:
`import olll

reduced_basis = olll.reduction([
  [1, 1, 1],
  [-1, 0, 2],
  [3, 5, 6],
], 0.75)

print(reduced_basis)`

The Trace back:

> runfile('C:/Users/Oren/Documents/Python Scripts/olll_test.py', wdir='C:/Users/Oren/Documents/Python Scripts')
Traceback (most recent call last):

>   File "<ipython-input-69-e12a7c66434f>", line 1, in <module>
>     runfile('C:/Users/Oren/Documents/Python Scripts/olll_test.py', wdir='C:/Users/Oren/Documents/Python Scripts')

>   File "C:\Users\Oren\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 685, in runfile
>     execfile(filename, namespace)

>   File "C:\Users\Oren\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 85, in execfile
>     exec(compile(open(filename, 'rb').read(), filename, 'exec'), namespace)

>   File "C:/Users/Oren/Documents/Python Scripts/olll_test.py", line 14, in <module>
>     ], 0.75)

>   File "C:\Users\Oren\Anaconda3\lib\site-packages\olll.py", line 93, in reduction
>     basis = list(map(Vector, basis))

>   File "C:\Users\Oren\Anaconda3\lib\site-packages\olll.py", line 73, in gramschmidt

> TypeError: 'GenericMeta' object does not support item assignment

Please let me know if there is any information missing

**Comment by orisano** [comment]
https://www.python.org/dev/peps/pep-0526/

sorry, supported version is 3.6 later.

please update your python version.
